/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFRAMES;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.jshell.spi.ExecutionControl;
import JFRAMES.Conector;
/**
 *
 * @author HP
 */
public class INICIO1 extends javax.swing.JFrame {

    Conector cc = new Conector();
    Connection con = (Connection) cc.Conectar();
    
    public INICIO1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        NOMBRE_USUARIO = new javax.swing.JTextField();
        CLAVE = new javax.swing.JPasswordField();
        CREAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        VOLVER = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 88, 160));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese sus Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 117, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre de Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clave");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 114, 72, 27));

        NOMBRE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 169, 31));

        NOMBRE_USUARIO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        getContentPane().add(NOMBRE_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 169, 33));

        CLAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        getContentPane().add(CLAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 169, 32));

        CREAR.setBackground(new java.awt.Color(153, 255, 0));
        CREAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CREAR.setForeground(new java.awt.Color(255, 255, 255));
        CREAR.setText("Crear");
        CREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARActionPerformed(evt);
            }
        });
        getContentPane().add(CREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 110, 34));

        CANCELAR.setBackground(new java.awt.Color(255, 51, 51));
        CANCELAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CANCELAR.setForeground(new java.awt.Color(255, 255, 255));
        CANCELAR.setText("Cancelar");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(CANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 110, 34));

        VOLVER.setBackground(new java.awt.Color(153, 204, 255));
        VOLVER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VOLVER.setForeground(new java.awt.Color(255, 255, 255));
        VOLVER.setText("Volver");
        VOLVER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        VOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVERActionPerformed(evt);
            }
        });
        getContentPane().add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 68, 27));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\TECSUP CICLO 2 DISEÑO Y DESARROLLO DE SOFTWARE\\PROGRAMACIÓN ORIENTADA A OBJETOS\\FondoCrearcuenta.PNG")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVERActionPerformed
        INICIO form= new INICIO();
                form.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_VOLVERActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
       ID.setText("");
       NOMBRE.setText("");
       NOMBRE_USUARIO.setText("");
       CLAVE.setText("");
    }//GEN-LAST:event_CANCELARActionPerformed

    private void CREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARActionPerformed
        try {
            crearusuario();
        } catch (SQLException ex) {
            Logger.getLogger(INICIO1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CREARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO1().setVisible(true);
            }
        });
    }

      public void crearusuario() throws SQLException{
        String pass= String.valueOf(CLAVE.getPassword());
        String SQL = "insert into encargados (id_encargado,usuario,clave,nombre)values(?,?,?,?)";
        
        try{
            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1,ID.getText());
            pst.setString(2,NOMBRE_USUARIO.getText());
            pst.setString(3,pass);
            pst.setString(4,NOMBRE.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro Exitoso");
        }catch (Exception e){
          JOptionPane.showMessageDialog(null,"Error de Registro : Ingrese otro ID o llene correctamente los campos ---> " + e.getMessage());
        }
      }   
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELAR;
    private javax.swing.JPasswordField CLAVE;
    private javax.swing.JButton CREAR;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField NOMBRE_USUARIO;
    private javax.swing.JButton VOLVER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
